package mocks

import (
	context "context"
	model "order/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// PaymentClient is an autogenerated-like mock type for the PaymentClient type.
type PaymentClient struct {
	mock.Mock
}

type PaymentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentClient) EXPECT() *PaymentClient_Expecter {
	return &PaymentClient_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function with given fields: ctx, orderUUID, userUUID, method.
func (_m *PaymentClient) PayOrder(ctx context.Context, orderUUID string, userUUID string, method model.PaymentMethod) (string, error) {
	ret := _m.Called(ctx, orderUUID, userUUID, method)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.PaymentMethod) (string, error)); ok {
		return rf(ctx, orderUUID, userUUID, method)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.PaymentMethod) string); ok {
		r0 = rf(ctx, orderUUID, userUUID, method)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, model.PaymentMethod) error); ok {
		r1 = rf(ctx, orderUUID, userUUID, method)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type PaymentClient_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call.
func (_e *PaymentClient_Expecter) PayOrder(ctx interface{}, orderUUID interface{}, userUUID interface{}, method interface{}) *PaymentClient_PayOrder_Call {
	return &PaymentClient_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, orderUUID, userUUID, method)}
}

func (_c *PaymentClient_PayOrder_Call) Run(run func(ctx context.Context, orderUUID string, userUUID string, method model.PaymentMethod)) *PaymentClient_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.PaymentMethod))
	})
	return _c
}

func (_c *PaymentClient_PayOrder_Call) Return(_a0 string, _a1 error) *PaymentClient_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentClient_PayOrder_Call) RunAndReturn(run func(context.Context, string, string, model.PaymentMethod) (string, error)) *PaymentClient_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentClient creates a new instance of PaymentClient.
func NewPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentClient {
	mock := &PaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
