package mocks

import (
	context "context"
	model "order/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// InventoryClient is an autogenerated-like mock type for the InventoryClient type.
type InventoryClient struct {
	mock.Mock
}

type InventoryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryClient) EXPECT() *InventoryClient_Expecter {
	return &InventoryClient_Expecter{mock: &_m.Mock}
}

// GetInventoryModels provides a mock function with given fields: ctx, uuids.
func (_m *InventoryClient) GetInventoryModels(ctx context.Context, uuids []string) ([]model.Part, error) {
	ret := _m.Called(ctx, uuids)

	if len(ret) == 0 {
		panic("no return value specified for GetInventoryModels")
	}

	var r0 []model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]model.Part, error)); ok {
		return rf(ctx, uuids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []model.Part); ok {
		r0 = rf(ctx, uuids)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]model.Part)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, uuids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type InventoryClient_GetInventoryModels_Call struct {
	*mock.Call
}

// GetInventoryModels is a helper method to define mock.On call.
func (_e *InventoryClient_Expecter) GetInventoryModels(ctx interface{}, uuids interface{}) *InventoryClient_GetInventoryModels_Call {
	return &InventoryClient_GetInventoryModels_Call{Call: _e.mock.On("GetInventoryModels", ctx, uuids)}
}

func (_c *InventoryClient_GetInventoryModels_Call) Run(run func(ctx context.Context, uuids []string)) *InventoryClient_GetInventoryModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *InventoryClient_GetInventoryModels_Call) Return(_a0 []model.Part, _a1 error) *InventoryClient_GetInventoryModels_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryClient_GetInventoryModels_Call) RunAndReturn(run func(context.Context, []string) ([]model.Part, error)) *InventoryClient_GetInventoryModels_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryClient creates a new instance of InventoryClient.
func NewInventoryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryClient {
	mock := &InventoryClient{}
	mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
